### PR TITLE
Change "ITrelloFacotry.Me" method to allow passing in non-default TrelloAuthorization

### LINKED ISSUE #313: Allow passing auth info to "Me()"
**Does Trello do something you can't automate with this library?  Can this library make doing something simpler?**
The `ITrelloFactory.Me()` method does not currently support passing in an instance of `TrelloAuthorization`, and instead reads the values from the static `TrelloAuthorization.Default`. It would be great if that limitation is removed by adding another overload that supports this argument.

**Describe alternatives you've considered**
It's possible to re-assign the static `TrelloAuthorization.Default` every time you need to perform a call for a different user. However, on a multi-threaded server handling requests for multiple users, this kind of solution will be either very dangerous (allowing for concurrency races) or very slow (if we were to, for example, lock every call to make sure settings are always correct).

**Additional context**
It seems like all other methods support this, which makes a lot of sense when you consider applications that serve many different users and manage a big set of user tokens. I think adding support for custom auth for `Me()` calls is more a standardization, making it more compatible with the rest of the library's API, than an actual feature.

### PR DESCRIPTION
**Pull request by nimrodolev**
resolves #313

### CODE REVIEW

**Comment by gregsdennis** [comment]
Looks like I need to update the build...

Also, tabs not spaces, please.

Since this is a breaking change anyway, please go ahead and remove the static `Member.Me` property.  Up to this point,  `Me` was special because I only wanted one. Now needs to be treated the same as all of the other entities.

**Comment by nimrodolev** [comment]
I'm not sure I understood what you meant. What static `Member.Me`? There's no `Me` on `IMember` or `Member`. There's the internal static `GetId` but that's still needed, as far as I understand.

**Comment by gregsdennis** [comment]
I must have been recalling old implementation (before the interfaces).  I used to have a static `Member.Me`.  I didn't have the code in front of me at the time.  Nevermind.

**Comment by gregsdennis** [comment]
Formatting is still off.  Are you using R#?

**Comment by nimrodolev** [comment]
Already fixed it, just didn't want to spam with alerts for no reason. Pushed now.

**Comment by gregsdennis** [comment]
Well, the tests are failing the same as the release branch, so it's probably working.  I have some things I need to do there.

I'm going to go ahead and pull this in, and fix the tests in my own time.

Thanks.

**Comment by nimrodolev** [comment]
Happy to help 👌

**Comment by gregsdennis** [comment]
Sorry.  I don't know what happened.  This should have gone out with 4.0.0.  I'll merge it in and release a 4.1.0.

**Pull request merged**
