### PR TITLE
Changed ReopenedBoard to ReopenBoard

### LINKED ISSUE #327: Just trying to get started: TargetInvocationException
I'm new to Manatee.Trello and just trying to get started. Here's what I've got (.NET Framework console app):

```
    class Program
    {
        static TrelloFactory factory;
        static void Main(string[] args)
        {
            Auth();
            GetBoards().Wait();
        }

        public static void Auth()
        {
            TrelloAuthorization.Default.AppKey = "APPKEY";
            TrelloAuthorization.Default.UserToken = "TOKEN";

            factory = new TrelloFactory();
        }

        public static async Task<List<Board>> GetBoards()
        {
            List<Board> result = new List<Board>();

            try
            {
                IMe me = await factory.Me();
                foreach (Board board in me.Boards)
                    result.Add(board);
            }
            catch (Exception ex)
            {

            }

            return result;
        }
    }
```

Whenever I run it, the `factory.Me()` line throws `Exception has been thrown by target of an invocation`. Am I doing something obviously wrong? I couldn't seem to find docs that contain, step-by-step, how to get started.

### PR DESCRIPTION
**Pull request by derekantrican**
You're going to hate this..... (minor typo: "reopened" should be "reopen")

Resolves #327

### CODE REVIEW

**Comment by gregsdennis** [comment]
Argh! Okay. Can you also bump the patch number in the version (4.2.3) and assembly version (4.2.3.0) in the main project file, then add an entry in `docs_source/release_notes.md`, please?

**Comment by gregsdennis** [comment]
Three inconsistency of the Trello API continues to astound me.

**Comment by derekantrican** [comment]
Ok, I believe I've updated the things you wanted (let me know if something is still missing)

**Comment by gregsdennis** [comment]
Yep. that looks good. Thanks.

**Comment by gregsdennis** [comment]
Apparently Trello is having sadness.

image

I'm going to wait for that to resolve so that the tests pass.  Then I'll merge this.

**Comment by gregsdennis** [comment]
they report good, and the build passed, so... merge!

**Pull request merged**
